### ISSUE TITLE
Could you please provide a simple usage in your ReadMe File? I am just starting the way of tensorflow. Thank you so much.

### ISSUE THREAD

**Issue by liuchjlu** [agnusmaximus/DistributedMNIST#1]

**Comment by agnusmaximus** [comment]
Sure! Here's a basic tutorial on how to use it -- https://github.com/agnusmaximus/snippets/blob/master/AWS%20%2B%20Inception%20Tensorflow.ipynb.

**Comment by agnusmaximus** [comment]
Let me know if there are any other problems / questions.
